import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bar(props) {
  const { nodes, materials } = useGLTF('/bar_scene.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-94.949, 0.088, 26.282]} rotation={[-0.003, 0.185, 0.001]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface664_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface665_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface666_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface667_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface668_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface669_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface670_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface671_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface672_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface673_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface674_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface675_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface676_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface677_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface678_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface679_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface680_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface681_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface682_light_0.geometry}
          material={materials.light}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface683_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface684_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface685_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface686_wood_0.geometry}
          material={materials.wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface687_blue_black_0.geometry}
          material={materials.blue_black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface688_silver_0.geometry}
          material={materials.silver}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface689_silver_0.geometry}
          material={materials.silver}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface690_silver_0.geometry}
          material={materials.silver}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface691_lambert12_0.geometry}
          material={materials.lambert12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface693_lambert12_0.geometry}
          material={materials.lambert12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface694_silver_0.geometry}
          material={materials.silver}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface695_silver_0.geometry}
          material={materials.silver}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface696_silver_0.geometry}
          material={materials.silver}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface697_silver_0.geometry}
          material={materials.silver}
        />
      </group>
      <group position={[13.402, 0.087, -13.486]} rotation={[0, 1.02, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface22_gold_0.geometry}
          material={materials.gold}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface22_dark_green_brawn_0.geometry}
          material={materials.dark_green_brawn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface22_glass_0.geometry}
          material={materials.glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface22_under_glass_0.geometry}
          material={materials.under_glass}
        />
      </group>
      <group position={[6.995, 0, -22.066]} rotation={[0, -0.297, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder46_white_0.geometry}
          material={materials.white}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder46_gold2_0.geometry}
          material={materials.gold2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube17_wood_middle_2_0.geometry}
          material={materials.wood_middle_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube17_wood_light2_0.geometry}
          material={materials.wood_light2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube17_dark_wood_0.geometry}
          material={materials.dark_wood}
        />
      </group>
      <group position={[-0.003, 0.148, 1.063]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface749_wood_light_3_0.geometry}
          material={materials.wood_light_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface750_wood_light_3_0.geometry}
          material={materials.wood_light_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface751_wood_0.geometry}
          material={materials.wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface752_wood_light_3_0.geometry}
          material={materials.wood_light_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface753_wood_light_3_0.geometry}
          material={materials.wood_light_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface754_wood_0.geometry}
          material={materials.wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface755_wood_0.geometry}
          material={materials.wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface756_wood_light_3_0.geometry}
          material={materials.wood_light_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface757_wood_light_3_0.geometry}
          material={materials.wood_light_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface758_wood_0.geometry}
          material={materials.wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface759_wood_light_3_0.geometry}
          material={materials.wood_light_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface760_wood_light_3_0.geometry}
          material={materials.wood_light_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface761_wood_light_3_0.geometry}
          material={materials.wood_light_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface762_wood_light_3_0.geometry}
          material={materials.wood_light_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface763_wood_light_3_0.geometry}
          material={materials.wood_light_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface764_wood_middle1_0.geometry}
          material={materials.wood_middle1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface765_wood_light2_0.geometry}
          material={materials.wood_light2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface766_wood_light_3_0.geometry}
          material={materials.wood_light_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface767_wood_light_3_0.geometry}
          material={materials.wood_light_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface768_wood_light_3_0.geometry}
          material={materials.wood_light_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface769_wood_light_3_0.geometry}
          material={materials.wood_light_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface770_wood_middle1_0.geometry}
          material={materials.wood_middle1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface771_wood_light_3_0.geometry}
          material={materials.wood_light_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface772_wood_light_3_0.geometry}
          material={materials.wood_light_3}
          position={[-0.371, 0, -0.174]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube91_dark_wood_0.geometry}
        material={materials.dark_wood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube91_gold2_0.geometry}
        material={materials.gold2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube91_wood_middle_2_0.geometry}
        material={materials.wood_middle_2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube91_wood_0.geometry}
        material={materials.wood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube91_black_0.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube91_black1_0.geometry}
        material={materials.black1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube91_wood_middle1_0.geometry}
        material={materials.wood_middle1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface499_gold3_0.geometry}
        material={materials.gold3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface499_lambert12_0.geometry}
        material={materials.lambert12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface499_wood_light1_0.geometry}
        material={materials.wood_light1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface592_black_0.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface592_gold3_0.geometry}
        material={materials.gold3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface592_silver_0.geometry}
        material={materials.silver}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface592_metal_0.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface592_wood_light1_0.geometry}
        material={materials.wood_light1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface592_wood_middle_0.geometry}
        material={materials.wood_middle}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface313_wood_light1_0.geometry}
        material={materials.wood_light1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface313_metal_0.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface313_silver_0.geometry}
        material={materials.silver}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface313_gold3_0.geometry}
        material={materials.gold3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface313_black_0.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface741_wood_middle1_0.geometry}
        material={materials.wood_middle1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface741_chear_seat_0.geometry}
        material={materials.chear_seat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface599_dark_green_brawn_0.geometry}
        material={materials.dark_green_brawn}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface599_dark_blue_0.geometry}
        material={materials.dark_blue}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface599_silver_0.geometry}
        material={materials.silver}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface599_gold3_0.geometry}
        material={materials.gold3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface599_black_0.geometry}
        material={materials.black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface599_wood_0.geometry}
        material={materials.wood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface748_wood_middle1_0.geometry}
        material={materials.wood_middle1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface748_chear_seat_0.geometry}
        material={materials.chear_seat}
      />
    </group>
  )
}

useGLTF.preload('/bar_scene.glb')