import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mountains(props) {
  const { nodes, materials } = useGLTF('/low_poly_mountain_scene.glb')
  return (
    <group scale={[20,20,20]} position={[0,-20,0]} rotation={[0,-2.2,0]} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={7.018}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_1.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_2.geometry}
            material={materials['Material.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_3.geometry}
            material={materials['Material.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_4.geometry}
            material={materials['Material.022']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_5.geometry}
            material={materials['Material.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_6.geometry}
            material={materials['Material.008']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_7.geometry}
            material={materials['Material.010']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_8.geometry}
            material={materials['Material.011']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_9.geometry}
            material={materials['Material.012']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_10.geometry}
            material={materials['Material.013']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_11.geometry}
            material={materials['Material.014']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_12.geometry}
            material={materials['Material.015']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_13.geometry}
            material={materials['Material.016']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_14.geometry}
            material={materials['Material.017']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_15.geometry}
            material={materials['Material.018']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_16.geometry}
            material={materials['Material.019']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_17.geometry}
            material={materials['Material.020']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_18.geometry}
            material={materials['Material.021']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_19.geometry}
            material={materials['Material.000']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_20.geometry}
            material={materials['Material.005']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/low_poly_mountain_scene.glb')

